### PR TITLE
GetDls Local

### PR DESCRIPTION
**Pull request by getdls**
Cpt Toad fixes

### CODE REVIEW

**Comment by getdls** [comment]
FFs.. I even tried  rebase  

Next time I'll just delete the whole tree and create a new branch.. its faster

**Comment by Crementif** [comment]
The code checks out, I guess we can merge. 👍

**Comment by getdls** [comment]
I prefer your excellency, but GetDls fine..

(what title?, I changed added DKC due to the confusion about calling it tropical freeze)

**Comment by Crementif** [comment]
Uh, meant the GetDls Local name of the pull request. It isn't very searchable.

**Comment by getdls** [comment]
Aaah.. I kept getting confused when dong the squash/rebase both were called master.. So I picked something NOT master

**Comment by Crementif** [comment]
Oh, glad you've got that covered. Just make sure you don't lose code, I had nightmares using git a fair amount of times when doing complete wipes.

**Comment by getdls** [comment]
Yea.. It's usually the opposite, we have to prove that the log is complete and unchanged.

**Pull request merged**
